---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
ratings:
  paths:
  - "**.py"
exclude_paths: []
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - 2968493abdc1b82db5bf209d02c1faaa
