version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: ^[Aa]pproved|LGTM|\+1|[Hh]ell [Yy]eah
      enabled: true
      reject_regex: ^Rejected
    required: 1
    reset_on_push: false
    users:
    - andrewmichaud
