language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - nightly

install:
    - python setup.py install
    - pip install coveralls
script:
    - coverage run --source=puckfetcher setup.py test
    - coverage report -m

after_success:
    - coveralls
