language: python

os:
    - linux

# TODO re-add PyPy when they get >=3.5 support.
python:
    - "3.6"
    - "3.5"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - python setup.py install
    - pip install coveralls
    - pip install mypy-lang

script:
    - |
      mypy --silent-imports \
      puckfetcher/config.py puckfetcher/subscription.py puckfetcher/__main__.py \
      puckfetcher/error.py puckfetcher/util.py \
      puckfetcher/test/test_config.py puckfetcher/test/test_subscription.py \
      puckfetcher/test/test_main.py puckfetcher/test/test_util.py \
      --disallow-untyped-defs --incremental --warn-no-return --show-column-numbers

    - coverage run --source=puckfetcher setup.py test
    - coverage report -m

after_success:
    - coveralls
