language: python

os:
    - linux

# TODO re-add PyPy when they get >=3.4 support.
python:
    - "3.5"
    - "3.4"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - python setup.py install
    - pip install coveralls

script:
    - coverage run --source=puckfetcher setup.py test
    - coverage report -m

after_success:
    - coveralls
