language:
    - python
python:
    - 2.7
    - 3.5
    - nightly

install:
    - python setup.py install
    - pip install coveralls
script:
    - coverage run --source=puckCatcher setup.py test

after_success:
    - coveralls
